name: Deploy to Firebase Hosting on Test Branch
on:
  push:
    branches:
      - test
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Install dependencies and build
      - run: npm ci && npm run build

      # Step 3: Deploy to Firebase Hosting (Test Channel)
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CHAI_WALEY }}
          channelId: test  # Custom channel for test branch
          projectId: chai-waley
