name: Firebase Deployment

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  build:
    name: Build Vite Project
    runs-on: ubuntu-22.04  # Explicitly use the stable version of Ubuntu
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3  # Updated to the latest version to avoid deprecated commands
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use the Node.js version required for your project
        
      - name: Install Dependencies
        run: npm ci  # Use `npm ci` for clean installs (faster and more reliable than `npm install`)
        
      - name: Build Project with Vite
        env:
          CI: false
        run: npm run build  # Build the Vite project

      - name: Archive Production Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist  # Vite outputs files to the `dist` directory by default

  deploy:
    name: Deploy to Firebase Hosting
    needs: build  # Ensure the deploy job runs only after a successful build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: dist  # Download the artifact to the correct directory

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v1.3.0
        with:
          args: deploy --only hosting  # Deploy only to hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
